%{
  #include <stdio.h>
  #include <stdlib.h>
  extern FILE *yyin, *yyout;
  extern void yyerror (char const *s);
  extern int yylex(void);
%}

%token T_TYPEREF T_STRING T_INTEGER T_KEYWORD_TYPE T_KEYWORD_HAS T_KEYWORD_FIELD T_KEYWORD_UNIQUE T_KEYWORD_IS T_KEYWORD_HASHED T_KEYWORD_TRANSIENT T_KEYWORD_IDENTIFYING T_KEYWORD_AUTO T_KEYWORD_LIMIT T_KEYWORD_PROTECTED T_KEYWORD_REQUIRED T_KEYWORD_OF T_OPENBRACE T_CLOSEBRACE T_SEMICOLON T_PERIOD T_COMMA

%%

FILE:           
  TYPEDEF_list;

TYPEDEF_list:   
  TYPEDEF TYPEDEF_list |
  TYPEDEF;

TYPEDEF:
  T_KEYWORD_TYPE T_TYPEREF T_OPENBRACE HASRULE_list T_CLOSEBRACE;

HASRULE_list:
  HASRULE T_SEMICOLON HASRULE_list |
  HASRULE HASRULE_list |
  HASRULE T_SEMICOLON |
  HASRULE;

HASRULE:
  T_KEYWORD_HAS T_KEYWORD_FIELD T_TYPEREF HASFIELDOPTION_list;

HASFIELDOPTION_list:
  HASFIELDOPTION T_COMMA HASFIELDOPTION_list |
  HASFIELDOPTION HASFIELDOPTION_list |
  /* empty */;

HASFIELDOPTION:
  T_KEYWORD_OF T_KEYWORD_TYPE T_TYPEREF |
  T_KEYWORD_LIMIT T_INTEGER |
  T_KEYWORD_IS T_KEYWORD_IDENTIFYING |
  T_KEYWORD_IS T_KEYWORD_REQUIRED |
  T_KEYWORD_IS T_KEYWORD_UNIQUE |
  T_KEYWORD_IS T_KEYWORD_PROTECTED |
  T_KEYWORD_IS T_KEYWORD_HASHED |
  T_KEYWORD_IS T_KEYWORD_TRANSIENT |
  T_KEYWORD_AUTO;

%%

void yyerror (char const *s) {
  fprintf (stderr, "Parse error: %s\n", s);
  exit(1);
}

int main(int argc, char const *argv[]) {
  yyin = fopen(argv[1], "r");
  return yyparse();
}
